# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'bambooPracticalExam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bambooPracticalExam
#pod 'Firebase/Analytics'
pod 'Firebase/Auth'
#pod 'Firebase/Firestore'
######pod 'Firebase/Storage'

  target 'bambooPracticalExamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bambooPracticalExamUITests' do
    # Pods for testing
  end

end
